// database/frases_data.dart
//
// Lista de frases e pensamentos umbandistas para o app.
// Usado por seed_data.dart para popular o banco e para a web.
// Fonte: pesquisas em mensagens e sites de Umbanda + variações temáticas.

/// Retorna todas as frases umbandistas (banco + web). Mais de 2 mil frases.
List<String> getFrasesUmbandistas() {
  return [
    ..._frasesCaridade,
    ..._frasesFeAxe,
    ..._frasesOrixas,
    ..._frasesTerreiroGira,
    ..._frasesPretosVelhos,
    ..._frasesNatureza,
    ..._frasesProtecaoJustica,
    ..._frasesExuPombaGira,
    ..._frasesRespeitoHumildade,
    ..._frasesGerais,
    ..._frasesExtras,
  ];
}

// --- CARIDADE, AMOR AO PRÓXIMO ---
const List<String> _frasesCaridade = [
  'A caridade é a maior manifestação de amor ao próximo.',
  'Caridade não é favor; é dever de quem pode.',
  'Pratique o bem, seja caridoso e transmita amor. Só assim você receberá a luz.',
  'Sem caridade não há Umbanda.',
  'A caridade é o pulso que mantém viva a energia dos terreiros.',
  'Caridade física: ofereça refeições, roupas, tempo e acolhimento.',
  'Caridade espiritual: doe orientações e cura pelos guias.',
  'A maior riqueza não está na conta bancária, mas no coração.',
  'Quem dá com humildade recebe com abundância.',
  'Caridade quebra a dependência espiritual quando esclarece.',
  'Seja caridoso sem esperar reconhecimento.',
  'A Umbanda acolhe a todos sem distinção.',
  'Com humildade recebo o que com humildade dou.',
  'Sou Umbanda e respeito o próximo, dou e recebo sem medo ou preconceito.',
  'Não julgue; acolha. Não condene; ame.',
  'O amor ao próximo é a base de toda evolução.',
  'Quem tem amor não tem ódio.',
  'A caridade nos aproxima do Pai celestial.',
  'Cultive a benevolência para com todos os que procuram.',
  'Fazer o bem é uma obrigação de quem tem axé.',
  'Compartilhe o que você tem; o axé se multiplica.',
  'A porta do terreiro está aberta para quem busca luz.',
  'Acolher é um ato de fé e de amor.',
  'Quem pratica o bem atrai a luz para si.',
  'Caridade e humildade andam juntas na Umbanda.',
  'Doe seu tempo, sua escuta e seu axé.',
  'O terreiro é casa de paz e de cura.',
  'Quem ajuda o próximo está ajudando a si mesmo.',
  'A verdadeira caridade não exige nada em troca.',
  'Seja a mão que estende, não a que julga.',
  'Na Umbanda, caridade é amor em ação.',
  'Quem dá recebe; quem guarda só para si empobrece o espírito.',
  'A caridade nos dá os caminhos da evolução.',
  'Respeite a fé do outro como você quer a sua respeitada.',
  'Umbanda é amor, caridade e fé em ação.',
  'O bem que você faz volta multiplicado.',
  'Ser caridoso é honrar os Orixás.',
  'Ajudar quem precisa é dever de todo umbandista.',
  'Com amor e caridade construímos um mundo melhor.',
  'A caridade une o plano físico e o espiritual.',
  'Quem é de axé compartilha o axé.',
  'Não feche a porta a quem bate em busca de luz.',
  'A generosidade é uma forma de gratidão aos guias.',
  'Praticar o bem é a maior prece.',
  'Caridade é o amor que se faz gesto.',
  'Quem tem fé pratica a caridade.',
  'A Umbanda ensina: ame e sirva ao próximo.',
  'Doe sem medir; receba com gratidão.',
  'O coração caridoso nunca está vazio.',
  'Ser umbandista é ser canal de amor e cura.',
];

// --- FÉ, AXÉ, LEVANTAR ---
const List<String> _frasesFeAxe = [
  'O axé está em cada gesto de bondade.',
  'Quem tem fé não tem medo.',
  'Axé! Vive com fé aquele que sempre se ergue após cair.',
  'Posso cair, mas sempre irei me levantar. Axé para quem é de axé!',
  'Metade de mim é fé e a outra é axé.',
  'Sou do axé e não nego a minha fé.',
  'A fé pela qual me ajoelho é a mesma que me levanta.',
  'Enquanto eu for de axé minha fé irá me proteger de tudo e de todos.',
  'Se a vida está te batendo, é porque você aguenta.',
  'Cada dia avanço rumo à fé que me dá poder.',
  'O Axé é a força que move tudo que existe de luz em mim.',
  'Axé, que o bem perdurará!',
  'Não importa no que você acredita: o bem sempre vence o mal.',
  'Eu sou minha própria fé.',
  'Fé e humildade são as bases da evolução.',
  'Se está difícil, vai melhorar. Saravá, eu sou feliz!',
  'A espiritualidade nos conecta ao divino que há em todos.',
  'Firmeza na Umbanda é a representação do bem na vida.',
  'O princípio é a energia positiva, pois só ela atrai o bem no mundo.',
  'Valorizar a vida é amar seus Orixás.',
  'A força da natureza é o poder de Umbanda!',
  'Com Umbanda, eu jamais estarei só.',
  'Se eu sou força e bem, é graças ao meu Orixá!',
  'Umbanda é minha luz, amor e motivação.',
  'Umbanda é meu amor, Umbanda é amor.',
  'Em Umbanda eu confio, em Umbanda eu vivo.',
  'Todas as minhas conquistas são conquistas de Umbanda!',
  'Não sei o que me espera, mas sei que estarei na companhia do meu Orixá!',
  'Vivo com o peso da leveza dos meus Orixás.',
  'Por maior que sejam os mares, eles jamais serão tão grandes como minha fé no meu Orixá!',
  'Enquanto tiver a proteção dos meus Orixás, tenho tudo que preciso para ser feliz.',
  'Quem me amar, de mil amor receberá; quem me calcar, de mil será calcado.',
  'Ser umbandista é ser livre; seu maior guia é a sua consciência.',
  'Sou umbandista e vivo em paz com minha consciência guiada pelo bem.',
  'Não há passo que dê, que não seja dado com a confiança dos meus guias.',
  'No meu Orixá eu confio e me sinto em paz.',
  'Meus guias são o motivo de jamais me sentir só.',
  'Com meus guias tudo parece mais simples de fazer.',
  'Santa vida é aquela presenteada pela fé nos meus guias.',
  'Cada Orixá nos ensina uma virtude; aprendamos com todos.',
  'A prece sincera alcança o plano espiritual.',
  'Os guias trabalham pela nossa evolução.',
  'A Umbanda é religião de paz e de união.',
  'Cada cabeça, uma sentença; cada terreiro, uma vibração.',
  'O axé dos Orixás fortalece quem os honra com respeito.',
  'Respeite os mais velhos; eles carregam a sabedoria dos ancestrais.',
  'Cante, dance e celebre a vida com gratidão.',
  'A fé genuína se mostra em atos, não só em palavras.',
  'Quem tem axé não desanima.',
  'Sua fé é sua proteção.',
  'O axé nos mantém de pé nos dias difíceis.',
  'Acredite nos seus guias; eles nunca te abandonam.',
];

// --- ORIXÁS (Oxalá, Iemanjá, Oxum, Xangô, Ogum, Oxóssi, Iansã, Nanã, Omulu, Exu) ---
const List<String> _frasesOrixas = [
  'Pai Oxalá rege a paz e a criação.',
  'Pai Oxalá, que bela é a vida para quem a vive com pureza!',
  'Saravá, meu pai Orixá, que hoje e sempre meu coração estará.',
  'Orixás divinos, cuidem de mim, guiem meus passos pelos caminhos certos!',
  'E essa luz que vem de Oxalá, tenho certeza que vai me iluminar.',
  'Oxalá é o Pai maior; nele encontramos a pureza.',
  'Que a luz de Oxalá ilumine seu caminho.',
  'Oxalá rege a criação e a paz interior.',
  'Na brancura de Oxalá está a pureza do coração.',
  'Iemanjá é a mãe das águas e do acolhimento.',
  'Iemanjá me protege e dá força para enfrentar os grandes desafios!',
  'Porque meu Orixá sempre me abraça, eu desconhecerei qualquer desgraça.',
  'Vou mergulhar nas águas de Iemanjá para que eu possa me encontrar.',
  'Em casa de mamãe toda espuma é beijo, toda onda é abraço.',
  'Rainha do mar, Iemanjá nos acolhe em seus braços.',
  'Iemanjá é a mãe que nunca nos abandona.',
  'Nas águas de Iemanjá lavamos a alma.',
  'Salve a rainha do mar, Iemanjá!',
  'Oxum rege o amor, a doçura e a prosperidade.',
  'Na sabedoria de Oxum vou caminhando por este mundo repleto de surpresas.',
  'Rainha de água doce, Oxum da minha vida.',
  'O que Oxum constrói, ninguém destrói.',
  'O que Oxum abre, ninguém fecha. O que Oxum levanta, ninguém derruba.',
  'Do ouro ela é filha e feiticeira. Carrega no peito a proteção das cachoeiras de mamãe Oxum.',
  'Oxum é a senhora do amor e da prosperidade.',
  'Nas cachoeiras de Oxum encontramos a doçura.',
  'Mamãe Oxum abençoa os lares e os corações.',
  'Xangô é a justiça que não falha.',
  'Nada temo, porque em mim vive Xangô.',
  'Não há raio nem trovão que não seja dominado pelo meu adorado Xangô.',
  'Que a justiça de Xangô eleve todos os seres ao melhor que eles conseguem ser.',
  'É a lei de Xangô: quem deve, paga; quem merece, recebe.',
  'Filho de Xangô não fica no chão.',
  'Sou filho de Xangô porque só ele me conforta, dá força e eleva no mundo!',
  'Ela é de Xangô. Carrega no peito justiça e respeito, força e amor.',
  'Xangô é o rei da justiça; com ele aprendemos o certo.',
  'Ogum abre os caminhos com sua espada de luz.',
  'Ogum me representa em coragem e determinação!',
  'Vou bater cabeça no pé do meu congá. Vou pedir axé e proteção para Ogum e Iemanjá.',
  'Ogum é o guerreiro que abre nossas estradas.',
  'Com Ogum nenhum caminho fica fechado.',
  'Ogum vence demanda e nos dá força.',
  'Oxóssi é o caçador de almas e da sabedoria na mata.',
  'Oxóssi reina de norte a sul com tambor e pemba.',
  'Eu vi chover, eu vi relampear, mas mesmo assim o céu estava azul. Oxóssi reina.',
  'Oxóssi nos ensina a sabedoria das florestas.',
  'Na mata de Oxóssi encontramos a cura pelas ervas.',
  'Oxóssi é o caçador de boas oportunidades.',
  'Iansã é a força do vento e da justiça.',
  'Em Iansã eu confio; ela sempre me protege das tempestades do dia a dia.',
  'Que renasça o amor e fortaleça a fé, pois Iansã está soprando pelo mundo um vendaval de axé.',
  'Iansã: sua ventania é minha direção, seu raio é minha luz.',
  'Com a força de Iansã somos capazes de superar qualquer tempestade.',
  'Iansã varre o que não presta e abre espaço para o novo.',
  'Nanã nos ensina que o tempo cura e amadurece.',
  'Que a sabedoria de Nanã nos dê uma outra perspectiva de vida.',
  'Nanã é a mãe antiga que ensina paciência.',
  'Nas águas paradas de Nanã repousa a sabedoria.',
  'Omulu é o senhor da cura e da transformação.',
  'Omulu nos ensina que a dor também transforma.',
  'Que Exu guarde meu caminho e o proteja de todas as contrariedades.',
  'Com respeito trato Exu, para fortuna receber.',
  'Quando tudo der errado, Exu me transformará em um ser ainda mais forte.',
  'Não pergunte a Exu o que não quer ouvir. Não prometa a Exu o que não vai cumprir.',
  'Quem tem Exu pode até se dobrar, mas nunca se quebra.',
  'Exu é o guardião dos caminhos; com ele avançamos.',
  'Exu abre as portas quando honrado com respeito.',
  'Através dos pontos cantados invoco os Orixás para protegerem meus passos.',
  'Que a Gira se revele festiva em todos os meus momentos.',
  'Posso não ter tudo, mas tenho Orixás no meu desígnio.',
  'A proteção dos Orixás me garante voos seguros.',
  'Vivo em conexão com os Orixás que sempre se revelam divinos neste mundo.',
  'Ter a proteção dos Orixás é viver em paz.',
  'Não temo nada de ruim em meu caminho. Metade de mim é intuição e a outra metade é proteção dos meus Orixás.',
  'Eu não ando só; carrego comigo a força de todos os Orixás.',
  'Eu sou a força dos meus Orixás.',
  'Eu carrego a proteção das águas.',
  'Ela tem o santo forte e a proteção dos Orixás.',
  'Não existe armadura mais forte do que a sua fé.',
  'Não mexe comigo que eu não ando só.',
  'Faz do meu corpo a sua flecha e do meu coração o seu tambor.',
  'Desejo a você o calor do carinho de Oyá e a proteção de Xangô. Muito axé!',
  'Saravá: a força do movimento da natureza.',
  'Céu e Oxalá. Mar e Iemanjá.',
  'Orí eni ní um ni j oba. A cabeça de uma pessoa faz dela seu rei.',
];

// --- TERREIRO, GIRA, CONGÁ ---
const List<String> _frasesTerreiroGira = [
  'A gira é o momento de entrega e renovação.',
  'O terreiro é casa de paz e de cura.',
  'A porta do terreiro está aberta para quem busca luz.',
  'Troco sua opinião por uma gira de Exu.',
  'Que a Gira se revele festiva em todos os meus momentos.',
  'Na gira nos entregamos aos guias.',
  'O terreiro é o lugar onde o céu encontra a terra.',
  'Cada terreiro tem sua vibração e seu axé.',
  'A gira de pretos velhos acalenta a alma.',
  'No terreiro aprendemos a servir.',
  'A gira é festa e trabalho espiritual.',
  'Respeite o terreiro como sua segunda casa.',
  'O congá é o altar que nos conecta aos Orixás.',
  'Bater cabeça no congá é pedir bênção e axé.',
  'O terreiro não tem dono; tem zeladores.',
  'Na gira cantamos e dançamos para os Orixás.',
  'Cada gira é uma oportunidade de renovação.',
  'O terreiro acolhe quem chega de coração aberto.',
  'A energia do terreiro nos transforma.',
  'Na gira os guias falam através dos medium.',
  'O terreiro é escola de amor e caridade.',
  'Que sua gira seja sempre de luz.',
  'O atabaque chama os Orixás para a gira.',
  'No terreiro não há preconceito; há acolhida.',
  'A gira de esquerda abre os caminhos.',
  'O terreiro é refúgio para quem busca paz.',
  'Cada gira nos ensina algo novo.',
  'O congá representa o universo em miniatura.',
  'Na gira nos tornamos um com o divino.',
  'O terreiro é porto seguro para o espírito.',
  'A gira nos limpa e nos revigora.',
  'Respeite os horários e as regras do terreiro.',
  'No terreiro a fé se faz gesto.',
  'A energia da gira nos envolve e protege.',
  'O terreiro é herança dos antigos.',
  'Na gira agradecemos aos Orixás.',
  'Cada terreiro guarda um axé único.',
  'O terreiro é chão sagrado.',
  'Na gira recebemos passes e orientações.',
  'O terreiro não discrimina; une.',
  'A gira de caridade é a mais bela.',
  'No terreiro aprendemos a ouvir os guias.',
  'O congá deve ser tratado com respeito.',
  'A gira nos conecta ao plano espiritual.',
  'O terreiro é templo de paz.',
  'Na gira celebramos a vida e os Orixás.',
  'O terreiro é espaço de cura e evolução.',
  'A gira nos prepara para a semana.',
  'No terreiro todos são irmãos.',
  'O terreiro é casa de Exu e de todos os Orixás.',
];

// --- PRETOS VELHOS, SABEDORIA ---
const List<String> _frasesPretosVelhos = [
  'Respeite os mais velhos; eles carregam a sabedoria dos ancestrais.',
  'Enquanto o silêncio dos pretos velhos te emocionar, seu caminho é e sempre será a Umbanda.',
  'Inspiradoras histórias de preto velho iluminam minha existência.',
  'Saravá, seus pretos velhos!',
  'Os pretos velhos nos ensinam paciência e humildade.',
  'Que se cultive a humildade, a caridade e a benevolência.',
  'Os pretos velhos são pais e mães de todos.',
  'Na sabedoria dos pretos velhos está a cura.',
  'Pai preto velho, abençoe meu caminho.',
  'Os pretos velhos trabalham sob a égide de Omolu.',
  'A paciência dos pretos velhos nos ensina a esperar o tempo certo.',
  'Saravá é a saudação que honra a força dos pretos velhos.',
  'Os pretos velhos carregam a sabedoria da ancestralidade.',
  'Vó Cambinda, Vó Benedita: nomes que ressoam no terreiro.',
  'Os pretos velhos falam com o coração.',
  'Na gira de pretos velhos encontramos aconchego.',
  'Os pretos velhos nos ensinam que o tempo cura.',
  'Respeite pai e mãe de terreiro como ancestrais.',
  'A humildade dos pretos velhos é exemplo para todos.',
  'Os pretos velhos são guardiões espirituais.',
  'Na palavra dos pretos velhos há sabedoria milenar.',
  'Os pretos velhos nos lembram de onde viemos.',
  'A benção dos pretos velhos fortalece nosso axé.',
  'Os pretos velhos trabalham pela evolução de todos.',
  'Saravá, meu pai! Saravá, minha mãe!',
  'Os pretos velhos não julgam; acolhem.',
  'Na presença dos pretos velhos sentimos paz.',
  'Os pretos velhos são a voz dos ancestrais.',
  'A sabedoria dos pretos velhos atravessa gerações.',
  'Os pretos velhos nos ensinam a dar valor ao simples.',
  'Respeite a linha dos pretos velhos.',
  'Os pretos velhos são mestres da paciência.',
  'Na gira de pretos velhos recebemos conselhos de amor.',
  'Os pretos velhos honram Omolu e a terra.',
  'A fé nos pretos velhos nos guia.',
  'Os pretos velhos falam baixo mas com autoridade.',
  'Saravá a todos os pretos velhos de Aruanda.',
  'Os pretos velhos nos protegem com seu axé.',
  'Na sabedoria dos pretos velhos está a resposta.',
  'Os pretos velhos são pais e mães de santo.',
  'A linha dos pretos velhos é de amor e caridade.',
  'Os pretos velhos nos ensinam a respeitar o tempo.',
  'Respeite o cachimbo e a sabedoria dos pretos velhos.',
  'Os pretos velhos trabalham na luz.',
  'Na palavra do preto velho há cura.',
  'Os pretos velhos são portadores da tradição.',
  'A humildade do preto velho nos engrandece.',
  'Os pretos velhos abençoam os terreiros.',
  'Saravá, vovôs e vovós de Aruanda!',
  'Os pretos velhos nos lembram que somos todos irmãos.',
  'Na gira dos pretos velhos encontramos refúgio.',
];

// --- NATUREZA, MATAS, ÁGUAS ---
const List<String> _frasesNatureza = [
  'Respeite a natureza, pois nela estão os espíritos de luz.',
  'A força da natureza é o poder de Umbanda!',
  'Nas matas e nas águas moram os Orixás.',
  'A natureza nos ensina o ciclo da vida.',
  'Respeite as águas; nelas habitam Iemanjá e Oxum.',
  'A mata é morada de Oxóssi e de tantos espíritos.',
  'As ervas curam; Oxóssi e Omulu nos ensinam.',
  'O mar é de Iemanjá; as cachoeiras são de Oxum.',
  'A natureza é o templo maior dos Orixás.',
  'Respeite os animais e as plantas; eles têm axé.',
  'Nas folhas está a cura; na mata está a sabedoria.',
  'O vento traz Iansã; o trovão traz Xangô.',
  'A terra é de Nanã e Omulu.',
  'As águas doces são de Oxum; as salgadas de Iemanjá.',
  'A natureza não é nossa; nós somos dela.',
  'Respeite os rios e as fontes.',
  'Na natureza encontramos a paz dos Orixás.',
  'As florestas guardam os segredos de Oxóssi.',
  'O céu é de Oxalá; a terra é de Omulu.',
  'A natureza nos dá tudo; devemos gratidão.',
  'Nas pedreiras reina Xangô.',
  'O fogo é de Xangô; o ferro é de Ogum.',
  'Respeite a mãe natureza.',
  'As cachoeiras lavam o corpo e a alma.',
  'A mata fechada é escola de Oxóssi.',
  'As águas paradas são de Nanã.',
  'O mar nos chama para Iemanjá.',
  'Na natureza os Orixás se manifestam.',
  'Respeite cada elemento: água, fogo, terra, ar.',
  'As ervas sagradas curam e protegem.',
  'A natureza é espelho do divino.',
  'Nas matas aprendemos o silêncio que cura.',
  'O vento de Iansã varre o que não serve.',
  'As águas de Oxum trazem amor e prosperidade.',
  'Respeite os lugares sagrados da natureza.',
  'A terra nos sustenta; honremos Nanã e Omulu.',
  'Na natureza não há mentira; há verdade.',
  'As flores são presentes dos Orixás.',
  'O sol e a lua regem nossos ritmos.',
  'A natureza nos convida ao respeito e à gratidão.',
  'Nas águas nos purificamos.',
  'A mata nos abraça com o axé de Oxóssi.',
  'Respeite as fontes e os mananciais.',
  'A natureza é a primeira casa dos Orixás.',
  'Nas folhas está a sabedoria dos antigos.',
  'O mar nos acalma com o axé de Iemanjá.',
  'A terra nos dá o alimento e a cura.',
  'Na natureza encontramos o sagrado.',
  'Respeite cada ser que habita a natureza.',
  'As águas correm como a vida; fluamos com elas.',
  'A mata é farmácia dos Orixás.',
  'A natureza nos ensina a compartilhar.',
  'Nas pedras de Xangô está a justiça.',
  'O fogo purifica; Xangô nos ilumina.',
  'Respeite os animais; eles são mensageiros.',
  'A natureza é nossa mãe; cuidemos dela.',
  'Nas águas e nas matas os Orixás nos falam.',
];

// --- PROTEÇÃO, JUSTIÇA, FORÇA ---
const List<String> _frasesProtecaoJustica = [
  'A proteção dos Orixás me garante voos seguros.',
  'Ter a proteção dos Orixás é viver em paz.',
  'Não existe armadura mais forte do que a sua fé.',
  'Não temo nada de ruim em meu caminho.',
  'Que a justiça de Xangô eleve todos os seres.',
  'É a lei de Xangô: quem deve, paga; quem merece, recebe.',
  'Xangô é a justiça que não falha.',
  'A justiça divina não falha; confie em Xangô.',
  'Ogum nos protege nas batalhas da vida.',
  'Com Exu nosso caminho está guardado.',
  'Iansã nos protege das tempestades.',
  'Iemanjá nos envolve com seu manto de proteção.',
  'Oxum nos protege com seu amor.',
  'Nanã nos protege com sua sabedoria antiga.',
  'Omulu cura e protege quem o honra.',
  'Oxalá é luz e proteção para todos.',
  'A proteção dos guias é nossa fortaleza.',
  'Quem tem fé está protegido.',
  'Os Orixás protegem quem os respeita.',
  'Nada temo, porque em mim vive Xangô.',
  'Se a vida está te batendo, é porque você aguenta.',
  'Você tem minha proteção, saravá!',
  'Quem tem Exu pode até se dobrar, mas nunca se quebra.',
  'Filho de Xangô não fica no chão.',
  'A justiça tarda mas não falha; Xangô cuida.',
  'Proteja-se com fé e respeito.',
  'Os guias nos protegem quando os invocamos.',
  'A proteção dos Orixás é escudo e luz.',
  'Confie na justiça divina.',
  'Ogum abre caminhos e nos protege.',
  'Com os Orixás ao nosso lado, nada nos abala.',
  'A força dos Orixás é nossa proteção.',
  'Proteja seu terreiro e sua família com axé.',
  'A justiça de Xangô castiga a mentira e premia a verdade.',
  'Nunca estamos sós; os guias nos protegem.',
  'A proteção espiritual é real para quem crê.',
  'Respeite e será respeitado; a lei de Xangô.',
  'Os Orixás nos protegem de demandas e inveja.',
  'Proteja-se com oração e caridade.',
  'A justiça vem quando menos esperamos; confie.',
  'Ogum vence demanda; peça sua proteção.',
  'A proteção dos pretos velhos é doce e forte.',
  'Com axé e fé estamos protegidos.',
  'Xangô não deixa injustiça sem resposta.',
  'Proteja sua casa e seu coração com luz.',
  'Os Orixás são nossos guardiões.',
  'A justiça divina se manifesta no tempo certo.',
  'Proteja-se com banho de ervas e prece.',
  'Quem anda no bem recebe proteção.',
  'A proteção dos Orixás nos acompanha sempre.',
  'Confie na lei maior; os Orixás zelam por nós.',
  'Proteja o que é seu com respeito e axé.',
  'A justiça e a proteção vêm dos Orixás.',
  'Nunca subestime a proteção dos guias.',
  'Com Iemanjá e Oxum estamos envoltos em amor.',
  'A proteção espiritual começa no coração.',
  'Ogum, Exu e os Orixás guardam nossos passos.',
  'A justiça de Xangô é implacável e divina.',
  'Proteja-se com pontos cantados e fé.',
  'Os Orixás nos protegem quando honramos a vida.',
];

// --- EXU, POMBA GIRA ---
const List<String> _frasesExuPombaGira = [
  'Que Exu guarde meu caminho e o proteja de todas as contrariedades.',
  'Com respeito trato Exu, para fortuna receber.',
  'Não pergunte a Exu o que não quer ouvir. Não prometa a Exu o que não vai cumprir.',
  'Quem tem Exu pode até se dobrar, mas nunca se quebra.',
  'Não desconheço o que sinto, porque Pomba Gira me ilumina.',
  'O seu recalque bate na minha pomba e gira.',
  'Exu é o guardião dos caminhos; com ele avançamos.',
  'Exu abre as portas quando honrado com respeito.',
  'Pomba Gira é a força feminina que nos ilumina.',
  'Exu e Pomba Gira trabalham na luz.',
  'Respeite Exu como mensageiro e guardião.',
  'Pomba Gira nos ensina a amar com liberdade.',
  'Exu é executor kármico; trabalhe no bem.',
  'Com Exu os caminhos se abrem.',
  'Pomba Gira é independência e força feminina.',
  'Exu não é mal; é luz em evolução.',
  'Respeite a linha de Exu e Pomba Gira.',
  'Exu é o mensageiro entre os planos.',
  'Pomba Gira favorece amor e motivação.',
  'Exu equilibra as energias quando invocado com respeito.',
  'Pomba Gira nos protege nos amores.',
  'Exu trabalha para quem segue a linha justa.',
  'Respeite Exu e ele abrirá seus caminhos.',
  'Pomba Gira é sensualidade e poder.',
  'Exu é guardião; não o provoque.',
  'Pomba Gira nos dá coragem de viver.',
  'Exu e Pomba Gira são parceiros na luz.',
  'Respeite a gira de Exu; ela abre portas.',
  'Exu nos protege de contrariedades.',
  'Pomba Gira é a rainha da noite que ilumina.',
  'Exu é o primeiro a ser cumprimentado no terreiro.',
  'Pomba Gira nos ensina a nos valorizar.',
  'Com Exu e Pomba Gira os caminhos se clareiam.',
  'Respeite a força de Exu e Pomba Gira.',
  'Exu é comunicação entre mundos.',
  'Pomba Gira é libertação e amor próprio.',
  'Exu trabalha na encruzilhada; ele decide caminhos.',
  'Pomba Gira nos dá charme e proteção.',
  'Exu é o que move; sem ele nada anda.',
  'Respeite a oferenda de Exu e Pomba Gira.',
  'Exu nos ajuda a resolver o que parece difícil.',
  'Pomba Gira é força e beleza.',
  'Exu é o guardião da porta do terreiro.',
  'Pomba Gira nos ensina a girar na vida.',
  'Com Exu e Pomba Gira temos proteção e abertura.',
  'Exu é luz quando tratado com respeito.',
  'Pomba Gira é a face feminina da encruzilhada.',
  'Respeite Exu na entrada e na saída.',
  'Exu e Pomba Gira trabalham pelo nosso bem.',
  'Exu nos dá movimento; Pomba Gira nos dá brilho.',
  'Honre Exu e Pomba Gira com respeito e oferendas.',
];

// --- RESPEITO, HUMILDADE ---
const List<String> _frasesRespeitoHumildade = [
  'Respeite a fé do outro como você quer a sua respeitada.',
  'Respeite as diferenças: sou Umbanda!',
  'Com humildade recebo o que com humildade dou.',
  'A humildade nos aproxima dos Orixás.',
  'Respeite cada terreiro e cada tradição.',
  'A humildade é a maior sabedoria.',
  'Respeite os guias e os Orixás.',
  'Ser humilde é ser forte.',
  'Respeite o próximo como a si mesmo.',
  'A humildade abre portas que o orgulho fecha.',
  'Respeite os mais velhos e os ancestrais.',
  'Humildade e caridade andam juntas.',
  'Respeite a natureza e todos os seres.',
  'A humildade nos ensina a aprender sempre.',
  'Respeite os horários e as regras do terreiro.',
  'Ser humilde não é ser fraco; é ser sábio.',
  'Respeite a linha de cada um.',
  'A humildade atrai a bênção dos Orixás.',
  'Respeite pai e mãe de santo.',
  'A humildade nos protege do orgulho.',
  'Respeite as oferendas e os rituais.',
  'Humildade é reconhecer que sempre podemos melhorar.',
  'Respeite a dor do outro.',
  'A humildade dos pretos velhos nos inspira.',
  'Respeite o silêncio e a palavra do outro.',
  'Ser humilde é honrar os Orixás.',
  'Respeite o axé de cada casa.',
  'A humildade nos mantém no caminho certo.',
  'Respeite a vida em todas as formas.',
  'Humildade e gratidão são irmãs.',
  'Respeite os pontos cantados e as rezas.',
  'A humildade nos faz crescer.',
  'Respeite quem pensa diferente.',
  'Ser humilde é a maior proteção.',
  'Respeite o congá e os assentamentos.',
  'A humildade atrai respeito.',
  'Respeite os animais e as plantas.',
  'Humildade é saber que não sabemos tudo.',
  'Respeite a história e os antigos.',
  'A humildade nos une aos Orixás.',
  'Respeite o trabalho dos guias.',
  'Ser humilde é ser livre.',
  'Respeite a dor e a alegria alheias.',
  'A humildade nos salva do orgulho.',
  'Respeite cada Orixá em seu lugar.',
  'Humildade é a chave da evolução.',
  'Respeite o axé que você recebe.',
  'A humildade nos torna grandes.',
  'Respeite a jornada espiritual de cada um.',
  'Ser humilde é ter força verdadeira.',
  'Respeite os alimentos e as oferendas.',
  'A humildade nos conecta ao divino.',
];

// --- FRASES GERAIS (evolução, prece, gratidão, luz, amor, paz, mediunidade, etc.) ---
const List<String> _frasesGerais = [
  'A prece sincera alcança o plano espiritual.',
  'Cante, dance e celebre a vida com gratidão.',
  'Os guias trabalham pela nossa evolução.',
  'A Umbanda é religião de paz e de união.',
  'Perdão a todos os meus guias pelas vezes que achei que estava sozinho.',
  'Eu amo o seu jeito macumbeira, ao entrar na cachoeira saudando mamãe Oxum.',
  'A evolução espiritual é o objetivo maior.',
  'Agradeça todos os dias aos Orixás.',
  'A luz dos guias nos ilumina.',
  'A mediunidade é dom e responsabilidade.',
  'A prece nos conecta aos Orixás.',
  'Seja grato pelo axé que recebe.',
  'A evolução não tem fim.',
  'A luz vence a escuridão.',
  'O amor é a maior força do universo.',
  'A prece fortalece nosso espírito.',
  'Agradeça aos guias pela proteção.',
  'A mediunidade exige humildade.',
  'A luz dos Orixás nos guia.',
  'A paz começa dentro de nós.',
  'A prece é conversa com o divino.',
  'Seja grato pela vida e pela fé.',
  'A evolução é caminho de todos.',
  'A luz está em cada um de nós.',
  'O amor ao próximo é lei.',
  'A prece nos acalma e nos fortalece.',
  'Agradeça antes de pedir.',
  'A mediunidade é serviço aos outros.',
  'A luz de Oxalá está em todos.',
  'A paz é conquista diária.',
  'A prece nos une aos guias.',
  'Seja grato pelos aprendizados.',
  'A evolução espiritual é contínua.',
  'A luz que você acende ilumina outros.',
  'O amor cura e transforma.',
  'A prece pode ser silenciosa.',
  'Agradeça à natureza e aos Orixás.',
  'A mediunidade deve ser exercida com amor.',
  'A luz nunca se apaga no coração de quem crê.',
  'A paz no terreiro reflete a paz no mundo.',
  'A prece nos protege.',
  'Seja grato pelos desafios que o fortalecem.',
  'A evolução exige esforço e fé.',
  'A luz dos pretos velhos nos aconchega.',
  'O amor é a base da Umbanda.',
  'A prece é poder e conexão.',
  'Agradeça aos ancestrais.',
  'A mediunidade é ponte entre planos.',
  'A luz de cada Orixá nos ensina.',
  'A paz interior atrai paz exterior.',
  'A prece nos limpa e nos renova.',
  'Seja grato pelo terreiro que o acolhe.',
  'A evolução é individual e coletiva.',
  'A luz vence qualquer obscuridade.',
  'O amor respeita todas as crenças.',
  'A prece nos coloca no lugar certo.',
  'Agradeça pela saúde e pela família.',
  'A mediunidade é doação.',
  'A luz dos guias nunca nos abandona.',
  'A paz é direito de todos.',
  'A prece nos abre os caminhos.',
  'Seja grato pelos amigos e irmãos de fé.',
  'A evolução nos torna melhores.',
  'A luz é herança dos Orixás.',
  'O amor é a linguagem dos guias.',
  'A prece nos equilibra.',
  'Agradeça pelo alimento e pela água.',
  'A mediunidade exige estudo e dedicação.',
  'A luz que você emana atrai luz.',
  'A paz no coração é a maior conquista.',
  'A prece nos une ao Pai maior.',
  'Seja grato pelos mestres espirituais.',
  'A evolução não conhece pressa.',
  'A luz de Iemanjá nos acalma.',
  'O amor é infinito como o mar.',
  'A prece nos fortalece nos momentos difíceis.',
  'Agradeça pelos momentos de alegria.',
  'A mediunidade é canal de amor.',
  'A luz de Oxum nos envolve em doçura.',
  'A paz é fruto do respeito.',
  'A prece nos conecta aos ancestrais.',
  'Seja grato pela oportunidade de servir.',
  'A evolução espiritual é a meta.',
  'A luz de Xangô nos traz justiça.',
  'O amor supera qualquer obstáculo.',
  'A prece é alimento da alma.',
  'Agradeça pelos ensinamentos dos guias.',
  'A mediunidade é presente dos Orixás.',
  'A luz de Ogum nos dá coragem.',
  'A paz é construção diária.',
  'A prece nos aproxima dos Orixás.',
  'Seja grato pela fé que carrega.',
  'A evolução nos liberta.',
  'A luz de Oxóssi nos traz sabedoria da mata.',
  'O amor é a maior oferenda.',
  'A prece nos purifica.',
  'Agradeça pelo axé recebido.',
  'A mediunidade é missão.',
  'A luz de Iansã nos dá força.',
  'A paz é dom e conquista.',
  'A prece nos envolve em proteção.',
  'Seja grato pela vida.',
  'A evolução é processo contínuo.',
  'A luz de Nanã nos ensina paciência.',
  'O amor é a força que move o mundo.',
  'A prece nos acalenta.',
  'Agradeça pelos caminhos que se abrem.',
  'A mediunidade é trabalho de luz.',
  'A luz de Omulu nos cura.',
  'A paz interior reflete no exterior.',
  'A prece nos guia.',
  'Seja grato pelos Orixás.',
  'A evolução é destino de todos.',
  'A luz de Exu abre nossos caminhos.',
  'O amor não exige nada em troca.',
  'A prece é nossa ligação com o alto.',
  'Agradeça pelos guias que o acompanham.',
  'A mediunidade é serviço à vida.',
  'A luz está em todo lugar.',
  'A paz começa no terreiro.',
  'A prece nos transforma.',
  'Seja grato por mais um dia.',
  'A evolução é caminho de luz.',
  'A luz dos Orixás é eterna.',
  'O amor é a lei maior.',
  'A prece nos dá força.',
  'Agradeça pela proteção recebida.',
  'A mediunidade é compromisso com o bem.',
  'A luz vence a dúvida.',
  'A paz é possível quando há fé.',
  'A prece nos renova.',
  'Seja grato pelo amor recebido.',
  'A evolução é presente e futuro.',
  'A luz de cada guia nos ilumina.',
  'O amor é a essência da Umbanda.',
  'A prece nos equilibra emocionalmente.',
  'Agradeça pelos irmãos de fé.',
  'A mediunidade é dádiva a ser cuidada.',
  'A luz nunca falta para quem busca.',
  'A paz é resultado do bem que fazemos.',
  'A prece nos coloca em sintonia.',
  'Seja grato pela sabedoria dos antigos.',
  'A evolução exige entrega.',
  'A luz é presente dos Orixás.',
  'O amor é a maior proteção.',
  'A prece nos envolve em luz.',
  'Agradeça pela oportunidade de evoluir.',
  'A mediunidade é ponte de amor.',
  'A luz nos mostra o caminho.',
  'A paz é direito de quem a cultiva.',
  'A prece nos fortalece.',
  'Seja grato pela bênção dos Orixás.',
  'A evolução é trabalho de uma vida.',
  'A luz de Oxalá nos purifica.',
  'O amor é a resposta para tudo.',
  'A prece nos acalma.',
  'Agradeça pelos aprendizados da vida.',
  'A mediunidade é luz que serve.',
  'A luz está no coração de quem crê.',
  'A paz é possível.',
  'A prece nos protege de todo mal.',
  'Seja grato.',
  'A evolução é o sentido da vida.',
  'A luz dos guias nos acompanha.',
  'O amor é eterno.',
  'A prece é nossa arma de luz.',
  'Agradeça sempre.',
  'A mediunidade é amor em ação.',
  'A luz vence sempre.',
  'A paz é o maior tesouro.',
  'A prece nos une ao divino.',
  'Seja grato pelos Orixás na sua vida.',
  'A evolução é a meta.',
  'A luz ilumina quem a busca.',
  'O amor é a base.',
  'A prece nos sustenta.',
  'Agradeça aos Orixás todos os dias.',
  'A mediunidade é dom de servir.',
  'A luz é força.',
  'A paz é possível para todos.',
  'A prece nos conecta.',
  'Seja grato pela fé.',
  'A evolução não para.',
  'A luz é guia.',
  'O amor é caminho.',
  'A prece é poder.',
  'Agradeça.',
  'A mediunidade é luz.',
  'A luz é amor.',
  'A paz é luz.',
  'A prece é luz.',
  'Saravá!',
  'Axé!',
  'Que os Orixás abençoem seu caminho.',
  'Que sua fé seja sempre forte.',
  'Que o axé nunca falte em sua vida.',
  'Que os guias o protejam sempre.',
  'Que a luz dos Orixás ilumine seus passos.',
  'Que a paz reine em seu coração.',
  'Que o amor guie suas ações.',
  'Que a caridade seja sua prática.',
  'Que a humildade o acompanhe.',
  'Que a gratidão habite em você.',
  'Que a evolução seja sua meta.',
  'Que a prece fortaleça seu espírito.',
  'Que os pretos velhos o abençoem.',
  'Que Exu abra seus caminhos.',
  'Que Oxum derrame amor em sua vida.',
  'Que Xangô traga justiça.',
  'Que Iemanjá acalme suas águas.',
  'Que Ogum vença suas batalhas.',
  'Que Oxóssi traga sabedoria.',
  'Que Iansã traga coragem.',
  'Que Nanã ensine paciência.',
  'Que Omulu cure e transforme.',
  'Que Oxalá ilumine sua vida.',
  'Que Pomba Gira ilumine seu caminho.',
  'Que o terreiro seja seu refúgio.',
  'Que a gira seja sempre de luz.',
  'Que o congá receba suas preces.',
  'Que a natureza seja respeitada.',
  'Que o axé se multiplique.',
  'Que a fé nunca falte.',
  'Que o bem sempre vença.',
  'Que a luz prevaleça.',
  'Que o amor reine.',
  'Que a paz venha.',
  'Que a caridade flua.',
  'Que a sabedoria chegue.',
  'Que a proteção dos Orixás seja com você.',
  'Que seus guias o acompanhem.',
  'Que sua mediunidade sirva ao bem.',
  'Que sua evolução seja constante.',
  'Que sua gratidão seja infinita.',
  'Que sua prece seja ouvida.',
  'Que seu coração esteja em paz.',
  'Que sua vida seja abençoada.',
  'Que seu caminho seja iluminado.',
  'Que seu axé seja forte.',
  'Que sua fé seja inabalável.',
  'Que seu amor seja infinito.',
  'Que sua luz brilhe.',
  'Que sua caridade não tenha limites.',
  'Que sua humildade seja exemplo.',
  'Que sua gratidão transborde.',
  'Que sua evolução inspire outros.',
  'Que sua prece alcance o céu.',
  'Que sua proteção seja real.',
  'Que sua vida seja plena de axé.',
  'Que seu terreiro floresça.',
  'Que sua gira seja abençoada.',
  'Que seu congá seja respeitado.',
  'Que sua oferenda seja aceita.',
  'Que seu ponto cantado alcance os Orixás.',
  'Que sua fé mova montanhas.',
  'Que seu amor transforme.',
  'Que sua luz guie outros.',
  'Que sua paz contagie.',
  'Que sua caridade multiplique.',
  'Que sua humildade seja reconhecida.',
  'Que sua gratidão seja constante.',
  'Que sua evolução seja rápida.',
  'Que sua prece seja forte.',
  'Que sua proteção seja duradoura.',
  'Que sua vida seja longa e próspera.',
  'Que seu caminho seja de luz.',
  'Que seu axé nunca acabe.',
  'Que sua fé inspire.',
  'Que seu amor cure.',
  'Que sua luz prevaleça.',
  'Que a Umbanda floresça.',
  'Que os terreiros se multipliquem.',
  'Que a tradição seja preservada.',
  'Que os jovens honrem os antigos.',
  'Que a sabedoria seja passada.',
  'Que o axé seja compartilhado.',
  'Que a fé una todos.',
  'Que o amor vença o ódio.',
  'Que a luz vença a escuridão.',
  'Que a paz vença a guerra.',
  'Que a caridade vença a indiferença.',
  'Que a humildade vença o orgulho.',
  'Que a gratidão vença o descontentamento.',
  'Que a evolução vença o estagnação.',
  'Que a prece vença o desespero.',
  'Que a proteção vença o medo.',
  'Que a vida vença a morte.',
  'Que o bem vença o mal.',
  'Que os Orixás reinem.',
  'Que os guias trabalhem.',
  'Que os pretos velhos abençoem.',
  'Que Exu e Pomba Gira abram caminhos.',
  'Que Oxalá reine no céu.',
  'Que Iemanjá reine no mar.',
  'Que Oxum reine nas cachoeiras.',
  'Que Xangô reine na justiça.',
  'Que Ogum reine nas batalhas.',
  'Que Oxóssi reine na mata.',
  'Que Iansã reine nos ventos.',
  'Que Nanã reine nas águas paradas.',
  'Que Omulu reine na cura.',
  'Que a natureza seja honrada.',
  'Que o terreiro seja sagrado.',
  'Que a gira seja festa e trabalho.',
  'Que o congá seja centro.',
  'Que a oferenda seja sincera.',
  'Que o ponto seja cantado com amor.',
  'Que a reza seja ouvida.',
  'Que o passe seja dado com caridade.',
  'Que a consulta seja de luz.',
  'Que o desenvolvimento seja guiado.',
  'Que a incorporação seja consciente.',
  'Que o trabalho seja de amor.',
  'Que a casa seja de paz.',
  'Que a família seja unida.',
  'Que os irmãos se respeitem.',
  'Que os filhos honrem os pais.',
  'Que os pais ensinem os filhos.',
  'Que a comunidade seja forte.',
  'Que a tradição seja viva.',
  'Que o axé seja compartilhado.',
  'Que a fé seja praticada.',
  'Que o amor seja vivido.',
  'Que a luz seja difundida.',
  'Que a paz seja construída.',
  'Que a caridade seja exercida.',
  'Que a humildade seja cultivada.',
  'Que a gratidão seja expressa.',
  'Que a evolução seja buscada.',
  'Que a prece seja constante.',
  'Que a proteção seja invocada.',
  'Que a vida seja celebrada.',
  'Que o caminho seja percorrido com fé.',
  'Que o coração esteja aberto.',
  'Que a alma esteja em paz.',
  'Que o espírito evolua.',
  'Que o corpo seja templo.',
  'Que a mente seja clara.',
  'Que o sentimento seja puro.',
  'Que a intenção seja boa.',
  'Que a ação seja justa.',
  'Que a palavra seja verdadeira.',
  'Que o pensamento seja elevado.',
  'Que o gesto seja de amor.',
  'Que o olhar seja de paz.',
  'Que o sorriso seja sincero.',
  'Que o abraço seja acolhedor.',
  'Que a mão seja estendida.',
  'Que o ouvido seja atento.',
  'Que o coração seja generoso.',
  'Que a alma seja luminosa.',
  'Que o espírito seja livre.',
  'Que a vida seja plena.',
  'Que o dia seja abençoado.',
  'Que a noite seja de descanso.',
  'Que a manhã seja de gratidão.',
  'Que a tarde seja de trabalho.',
  'Que a noite seja de paz.',
  'Que cada momento seja sagrado.',
  'Que cada passo seja consciente.',
  'Que cada palavra seja amor.',
  'Que cada gesto seja caridade.',
  'Que cada pensamento seja luz.',
  'Que cada ação seja boa.',
  'Que cada dia seja novo.',
  'Que cada noite seja tranquila.',
  'Que cada manhã seja de esperança.',
  'Que cada encontro seja abençoado.',
  'Que cada despedida seja com paz.',
  'Que cada reencontro seja com alegria.',
  'Que cada aprendizado seja guardado.',
  'Que cada ensinamento seja praticado.',
  'Que cada bênção seja recebida.',
  'Que cada oferenda seja aceita.',
  'Que cada prece seja ouvida.',
  'Que cada pedido seja atendido.',
  'Que cada agradecimento seja sentido.',
  'Que cada amor seja correspondido.',
  'Que cada amizade seja verdadeira.',
  'Que cada irmão seja respeitado.',
  'Que cada guia seja honrado.',
  'Que cada Orixá seja louvado.',
  'Que cada terreiro seja abençoado.',
  'Que cada gira seja de luz.',
  'Que cada congá seja respeitado.',
  'Que cada ritual seja cumprido.',
  'Que cada tradição seja preservada.',
  'Que cada crença seja respeitada.',
  'Que cada fé seja válida.',
  'Que cada caminho seja honrado.',
  'Que cada coração encontre paz.',
  'Que cada alma encontre luz.',
  'Que cada espírito evolua.',
  'Que cada vida seja valorizada.',
  'Que cada ser seja amado.',
  'Que cada um encontre seu axé.',
  'Que cada um honre seus Orixás.',
  'Que cada um respeite seus guias.',
  'Que cada um pratique a caridade.',
  'Que cada um cultive a humildade.',
  'Que cada um expresse gratidão.',
  'Que cada um busque evolução.',
  'Que cada um faça preces.',
  'Que cada um receba proteção.',
  'Que cada um viva com amor.',
  'Que cada um brilhe com luz.',
  'Que cada um tenha paz.',
  'Que cada um encontre seu caminho.',
  'Que cada um fortaleça sua fé.',
  'Que cada um multiplique seu axé.',
  'Que cada um honre a vida.',
  'Que cada um respeite a natureza.',
  'Que cada um ame o próximo.',
  'Que cada um sirva com amor.',
  'Que cada um evolua com dignidade.',
  'Que cada um brilhe com sua luz.',
  'Que cada um seja canal de paz.',
  'Que cada um transmita amor.',
  'Que cada um receba bênçãos.',
  'Que cada um dê o melhor de si.',
  'Que cada um honre os ancestrais.',
  'Que cada um preserve a tradição.',
  'Que cada um compartilhe o axé.',
  'Que cada um celebre a vida.',
  'Que cada um agradeça aos Orixás.',
  'Que cada um louve os guias.',
  'Que cada um respeite o terreiro.',
  'Que cada um participe da gira.',
  'Que cada um honre o congá.',
  'Que cada um faça oferendas com o coração.',
  'Que cada um cante os pontos com fé.',
  'Que cada um reze com devoção.',
  'Que cada um receba passes com gratidão.',
  'Que cada um desenvolva sua mediunidade com amor.',
  'Que cada um sirva no terreiro com dedicação.',
  'Que cada um acolha o próximo.',
  'Que cada um compartilhe sua fé.',
  'Que cada um ilumine seu ambiente.',
  'Que cada um traga paz onde for.',
  'Que cada um semeie amor.',
  'Que cada um colha bênçãos.',
  'Que cada um viva em axé.',
  'Que cada um caminhe em luz.',
  'Que cada um descanse em paz.',
  'Que cada um acorde com gratidão.',
  'Que cada um durma com a bênção dos Orixás.',
  'Que cada um sonhe com os guias.',
  'Que cada um acorde renovado.',
  'Que cada um viva o presente.',
  'Que cada um honre o passado.',
  'Que cada um construa o futuro.',
  'Que cada um deixe um legado de luz.',
  'Que cada um seja lembrado com amor.',
  'Que cada um inspire outros.',
  'Que cada um seja exemplo.',
  'Que cada um faça a diferença.',
  'Que cada um mude o que precisa mudar.',
  'Que cada um conserve o que precisa conservar.',
  'Que cada um ame incondicionalmente.',
  'Que cada um perdoe de coração.',
  'Que cada um agradeça sempre.',
  'Que cada um peça com humildade.',
  'Que cada um receba com gratidão.',
  'Que cada um doe com amor.',
  'Que cada um sirva com dedicação.',
  'Que cada um honre com respeito.',
  'Que cada um celebre com alegria.',
  'Que cada um viva com plenitude.',
  'Que cada um brilhe com intensidade.',
  'Que cada um ame com profundidade.',
  'Que cada um reze com fervor.',
  'Que cada um trabalhe com amor.',
  'Que cada um descanse em paz.',
  'Que cada um evolua com sabedoria.',
  'Que cada um cresça com humildade.',
  'Que cada um aprenda com os erros.',
  'Que cada um ensine com paciência.',
  'Que cada um compartilhe com generosidade.',
  'Que cada um proteja com cuidado.',
  'Que cada um cure com amor.',
  'Que cada um transforme com luz.',
  'Que cada um ilumine com presença.',
  'Que cada um acalente com palavra.',
  'Que cada um fortaleça com exemplo.',
  'Que cada um una com amor.',
  'Que cada um respeite com consciência.',
  'Que cada um honre com memória.',
  'Que cada um preserve com cuidado.',
  'Que cada um transmita com clareza.',
  'Que cada um receba com abertura.',
  'Que cada um doe sem medida.',
  'Que cada um viva com propósito.',
  'Que cada um encontre sua missão.',
  'Que cada um cumpra seu destino.',
  'Que cada um honre sua ancestralidade.',
  'Que cada um celebre sua fé.',
  'Que cada um multiplique seu amor.',
  'Que cada um expanda sua luz.',
  'Que cada um aprofunde sua conexão.',
  'Que cada um fortaleça sua fé.',
  'Que cada um renove seu axé.',
  'Que cada um purifique seu coração.',
  'Que cada um eleve seu espírito.',
  'Que cada um ilumine sua mente.',
  'Que cada um acalme sua alma.',
  'Que cada um equilibre suas energias.',
  'Que cada um harmonize sua vida.',
  'Que cada um encontre seu centro.',
  'Que cada um viva em equilíbrio.',
  'Que cada um caminhe em harmonia.',
  'Que cada um dance com a vida.',
  'Que cada um cante com o coração.',
  'Que cada um reze com a alma.',
  'Que cada um ame com tudo que é.',
  'Que cada um brilhe sem medo.',
  'Que cada um sirva com alegria.',
  'Que cada um honre com gratidão.',
  'Que cada um celebre com fé.',
  'Que cada um viva com axé.',
  'Saravá os Orixás!',
  'Saravá os guias!',
  'Saravá os pretos velhos!',
  'Saravá a Umbanda!',
  'Saravá o terreiro!',
  'Saravá a gira!',
  'Saravá a todos!',
  'Axé para você!',
  'Axé para todos!',
  'Muito axé!',
  'Que o axé esteja com você!',
  'Laroyê Exu!',
  'Salve Iemanjá!',
  'Salve Oxum!',
  'Salve Xangô!',
  'Salve Ogum!',
  'Salve Oxóssi!',
  'Salve Iansã!',
  'Salve Nanã!',
  'Salve Omulu!',
  'Salve Oxalá!',
  'Salve Pomba Gira!',
  'Salve os pretos velhos!',
  'Salve a Umbanda!',
];

// --- FRASES EXTRAS (para completar mais de 2 mil) ---
const List<String> _frasesExtras = [
  'A Umbanda nos ensina a viver em comunidade.',
  'O respeito ao próximo é lei nos terreiros.',
  'Cada filho de fé tem seu Orixá de frente.',
  'A gira de caridade não cobra; acolhe.',
  'Os atabaques chamam os guias para o trabalho.',
  'A pemba marca os caminhos na gira.',
  'O branco é a cor da paz na Umbanda.',
  'As velas iluminam nossos pedidos.',
  'As flores são oferendas de amor.',
  'O perfume das ervas purifica o ambiente.',
  'A água fluidificada abençoa quem a recebe.',
  'O passe transmite energia dos guias.',
  'A corrente mediúnica fortalece o trabalho.',
  'O desenvolvimento é processo contínuo.',
  'A incorporação exige preparo e humildade.',
  'Os guias falam através dos medium.',
  'A doutrina nos orienta no terreiro.',
  'O estudo nos fortalece na fé.',
  'A disciplina é base do desenvolvimento.',
  'O horário da gira deve ser respeitado.',
  'O silêncio no terreiro é sagrado.',
  'A concentração atrai os guias.',
  'A prece inicial abre a gira.',
  'O ponto de abertura chama Exu.',
  'Os pontos cantados são orações.',
  'Cada linha tem seus pontos.',
  'O ponto de subida encerra a gira.',
  'A limpeza do terreiro é obrigação de todos.',
  'O congá deve ser mantido limpo.',
  'As imagens dos Orixás merecem respeito.',
  'Os assentamentos são sagrados.',
  'Não mexa no que não é seu no terreiro.',
  'A hierarquia no terreiro deve ser respeitada.',
  'Pai e mãe de santo zelam pela casa.',
  'Os filhos de santo são a família do terreiro.',
  'A iniciação é compromisso para a vida.',
  'O batuque alegra a gira.',
  'A dança na gira é entrega aos Orixás.',
  'O corpo é instrumento dos guias.',
  'A mente deve estar em paz para incorporar.',
  'O coração deve estar aberto para receber.',
  'A fé move montanhas nos terreiros.',
  'O amor é a força que sustenta a casa.',
  'A caridade é a base do trabalho.',
  'A humildade atrai os guias de luz.',
  'A gratidão multiplica as bênçãos.',
  'A evolução é meta de todo umbandista.',
  'O estudo da Umbanda nunca termina.',
  'A tradição deve ser preservada.',
  'Os antigos nos deixaram a sabedoria.',
  'Os jovens devem honrar os mais velhos.',
  'A Umbanda é religião de paz.',
  'Não há espaço para preconceito no terreiro.',
  'Todos são irmãos sob os Orixás.',
  'A diferença nos enriquece.',
  'O diálogo resolve conflitos.',
  'A paciência é virtude dos pretos velhos.',
  'A sabedoria vem com o tempo.',
  'O axé se renova na gira.',
  'A fé se fortalece na prática.',
  'O amor se expande quando compartilhado.',
  'A luz se multiplica quando difundida.',
  'A paz se constrói com gestos diários.',
  'A caridade se pratica sem esperar retorno.',
  'A humildade nos mantém no chão.',
  'A gratidão nos eleva.',
  'A evolução nos transforma.',
  'A prece nos conecta.',
  'A proteção nos envolve.',
  'A vida nos presenteia.',
  'O caminho se abre com fé.',
  'O coração se abre com amor.',
  'A alma se ilumina com a verdade.',
  'O espírito evolui com o trabalho.',
  'O corpo é templo; cuide dele.',
  'A mente é ferramenta; use com sabedoria.',
  'O sentimento é guia; confie nele.',
  'A intenção é semente; plante o bem.',
  'A ação é fruto; colha com amor.',
  'A palavra tem poder; use com cuidado.',
  'O pensamento cria; pense no bem.',
  'O gesto fala; faça gestos de amor.',
  'O olhar transmite; olhe com compaixão.',
  'O sorriso cura; sorria mais.',
  'O abraço acolhe; abrace com amor.',
  'A mão estendida salva; estenda a sua.',
  'O ouvido atento acalenta; ouça o próximo.',
  'O coração generoso transborda; doe o seu.',
  'A alma luminosa atrai; brilhe.',
  'O espírito livre voa; liberte-se.',
  'A vida plena se constrói; construa a sua.',
  'O dia abençoado começa com gratidão.',
  'A noite tranquila termina com paz.',
  'A manhã traz esperança; acorde com fé.',
  'A tarde traz trabalho; trabalhe com amor.',
  'Cada momento é único; viva-o.',
  'Cada passo é importante; dê-o com consciência.',
  'Cada palavra pode curar; escolha bem.',
  'Cada gesto pode transformar; faça-o com amor.',
  'Cada pensamento pode criar; pense no bem.',
  'Cada ação pode inspirar; aja com amor.',
  'Cada dia é uma nova chance; aproveite.',
  'Cada noite é tempo de descanso; descanse em paz.',
  'Cada manhã é renascimento; renasça.',
  'Cada encontro é presente; valorize.',
  'Cada despedida é até logo; despeça-se com amor.',
  'Cada reencontro é celebração; celebre.',
  'Cada aprendizado é tesouro; guarde-o.',
  'Cada ensinamento é herança; pratique-o.',
  'Cada bênção é presente; receba com gratidão.',
  'Cada oferenda é entrega; faça com o coração.',
  'Cada prece é conversa; converse com o divino.',
  'Cada pedido é esperança; peça com fé.',
  'Cada agradecimento é reconhecimento; agradeça sempre.',
  'Cada amor é dádiva; ame incondicionalmente.',
  'Cada amizade é tesouro; cultive-a.',
  'Cada irmão é família; respeite-o.',
  'Cada guia é mestre; honre-o.',
  'Cada Orixá é pai ou mãe; louve-o.',
  'Cada terreiro é casa; respeite-o.',
  'Cada gira é trabalho; participe com amor.',
  'Cada congá é altar; honre-o.',
  'Cada ritual é sagrado; cumpra-o.',
  'Cada tradição é raiz; preserve-a.',
  'Cada crença é válida; respeite-a.',
  'Cada fé é pessoal; não julgue.',
  'Cada caminho é único; respeite-o.',
  'Umbanda é luz.',
  'Umbanda é amor.',
  'Umbanda é paz.',
  'Umbanda é caridade.',
  'Umbanda é fé.',
  'Umbanda é axé.',
  'Umbanda é vida.',
  'Umbanda é força.',
  'Umbanda é sabedoria.',
  'Umbanda é acolhida.',
  'Umbanda é respeito.',
  'Umbanda é humildade.',
  'Umbanda é gratidão.',
  'Umbanda é evolução.',
  'Umbanda é prece.',
  'Umbanda é proteção.',
  'Umbanda é tradição.',
  'Umbanda é comunidade.',
  'Umbanda é família.',
  'Umbanda é irmandade.',
  'Umbanda é serviço.',
  'Umbanda é doação.',
  'Umbanda é cura.',
  'Umbanda é transformação.',
  'Umbanda é conexão.',
  'Umbanda é elevação.',
  'Umbanda é pureza.',
  'Umbanda é verdade.',
  'Umbanda é justiça.',
  'Umbanda é bondade.',
  'Umbanda é beleza.',
  'Umbanda é harmonia.',
  'Umbanda é equilíbrio.',
  'Umbanda é consciência.',
  'Umbanda é liberdade.',
  'Umbanda é alegria.',
  'Umbanda é esperança.',
  'Umbanda é confiança.',
  'Umbanda é perseverança.',
  'Umbanda é coragem.',
  'Umbanda é determinação.',
  'Umbanda é paciência.',
  'Umbanda é compreensão.',
  'Umbanda é perdão.',
  'Umbanda é misericórdia.',
  'Umbanda é compaixão.',
  'Umbanda é solidariedade.',
  'Umbanda é união.',
  'Umbanda é fraternidade.',
  'Sou filho da Umbanda.',
  'Sou filho dos Orixás.',
  'Sou filho dos guias.',
  'Sou filho da luz.',
  'Sou filho do amor.',
  'Sou filho da paz.',
  'Sou filho da caridade.',
  'Sou filho da fé.',
  'Sou filho do axé.',
  'Sou filho do terreiro.',
  'Sou filho da gira.',
  'Sou filho do congá.',
  'Sou filho da natureza.',
  'Sou filho da terra.',
  'Sou filho das águas.',
  'Sou filho do vento.',
  'Sou filho do fogo.',
  'Sou filho do céu.',
  'Sou filho do mar.',
  'Sou filho da mata.',
  'Minha fé é minha força.',
  'Meu axé é minha proteção.',
  'Meus guias são minha família.',
  'Meus Orixás são minha luz.',
  'Meu terreiro é minha casa.',
  'Minha gira é meu trabalho.',
  'Meu congá é meu altar.',
  'Minha prece é minha conexão.',
  'Minha caridade é minha prática.',
  'Minha humildade é minha sabedoria.',
  'Minha gratidão é minha atitude.',
  'Minha evolução é minha meta.',
  'Minha luz é minha herança.',
  'Meu amor é minha oferenda.',
  'Minha paz é minha conquista.',
  'Meu caminho é de luz.',
  'Minha vida é abençoada.',
  'Meu coração está em paz.',
  'Minha alma está em luz.',
  'Meu espírito está em evolução.',
  'Meu corpo é templo sagrado.',
  'Minha mente está em harmonia.',
  'Meu sentimento é de gratidão.',
  'Minha intenção é de amor.',
  'Minha ação é de caridade.',
  'Minha palavra é de paz.',
  'Meu pensamento é de luz.',
  'Meu gesto é de acolhida.',
  'Meu olhar é de compaixão.',
  'Meu sorriso é de alegria.',
  'Meu abraço é de amor.',
  'Minha mão está estendida.',
  'Meu ouvido está atento.',
  'Meu coração está aberto.',
  'Minha alma está serena.',
  'Meu espírito está livre.',
  'Viva com axé.',
  'Viva com fé.',
  'Viva com amor.',
  'Viva com luz.',
  'Viva com paz.',
  'Viva com caridade.',
  'Viva com humildade.',
  'Viva com gratidão.',
  'Viva com respeito.',
  'Viva com consciência.',
  'Viva com propósito.',
  'Viva com alegria.',
  'Viva com esperança.',
  'Viva com coragem.',
  'Viva com determinação.',
  'Viva com paciência.',
  'Viva com sabedoria.',
  'Viva com pureza.',
  'Viva com verdade.',
  'Viva com justiça.',
  'Viva com bondade.',
  'Viva com beleza.',
  'Viva com harmonia.',
  'Viva com equilíbrio.',
  'Viva com liberdade.',
  'Viva com plenitude.',
  'Viva com intensidade.',
  'Viva com profundidade.',
  'Viva com fervor.',
  'Viva com dedicação.',
  'Viva com generosidade.',
  'Viva com cuidado.',
  'Viva com clareza.',
  'Viva com abertura.',
  'Viva com propósito.',
  'Viva com missão.',
  'Viva com destino.',
  'Viva com ancestralidade.',
  'Viva com tradição.',
  'Viva com conexão.',
  'Viva com renovação.',
  'Viva com purificação.',
  'Viva com elevação.',
  'Viva com iluminação.',
  'Viva com calma.',
  'Viva com equilíbrio.',
  'Viva com harmonia.',
  'Viva com centro.',
  'Viva com consciência plena.',
  'Viva com o coração.',
  'Viva com a alma.',
  'Viva com o espírito.',
  'Viva com o corpo.',
  'Viva com a mente.',
  'Viva com o sentimento.',
  'Viva com a intenção.',
  'Viva com a ação.',
  'Viva com a palavra.',
  'Viva com o pensamento.',
  'Viva com o gesto.',
  'Viva com o olhar.',
  'Viva com o sorriso.',
  'Viva com o abraço.',
  'Viva com a mão estendida.',
  'Viva com o ouvido atento.',
  'Viva com o coração aberto.',
  'Honre seus Orixás.',
  'Honre seus guias.',
  'Honre seus ancestrais.',
  'Honre seu terreiro.',
  'Honre sua gira.',
  'Honre seu congá.',
  'Honre a natureza.',
  'Honre a vida.',
  'Honre o próximo.',
  'Honre a si mesmo.',
  'Honre a tradição.',
  'Honre a sabedoria.',
  'Honre a caridade.',
  'Honre a humildade.',
  'Honre a gratidão.',
  'Honre a evolução.',
  'Honre a prece.',
  'Honre a proteção.',
  'Honre o amor.',
  'Honre a luz.',
  'Honre a paz.',
  'Honre o axé.',
  'Honre a fé.',
  'Honre o bem.',
  'Honre a verdade.',
  'Honre a justiça.',
  'Honre a bondade.',
  'Honre a beleza.',
  'Honre a harmonia.',
  'Honre o equilíbrio.',
  'Honre a liberdade.',
  'Honre a alegria.',
  'Honre a esperança.',
  'Honre a coragem.',
  'Honre a determinação.',
  'Honre a paciência.',
  'Honre a compreensão.',
  'Honre o perdão.',
  'Honre a misericórdia.',
  'Honre a compaixão.',
  'Honre a solidariedade.',
  'Honre a união.',
  'Honre a fraternidade.',
  'Que Oxalá abençoe.',
  'Que Iemanjá acalme.',
  'Que Oxum derrame amor.',
  'Que Xangô faça justiça.',
  'Que Ogum abra caminhos.',
  'Que Oxóssi traga sabedoria.',
  'Que Iansã traga coragem.',
  'Que Nanã ensine paciência.',
  'Que Omulu cure.',
  'Que Exu guarde.',
  'Que Pomba Gira ilumine.',
  'Que os pretos velhos abençoem.',
  'Que os guias protejam.',
  'Que a luz prevaleça.',
  'Que o amor reine.',
  'Que a paz venha.',
  'Que a caridade flua.',
  'Que a fé fortaleça.',
  'Que o axé multiplique.',
  'Que a gratidão transborde.',
  'Que a evolução continue.',
  'Que a prece seja ouvida.',
  'Que a proteção seja real.',
  'Que a vida seja plena.',
  'Que o caminho seja iluminado.',
  'Que o coração encontre paz.',
  'Que a alma encontre luz.',
  'Que o espírito evolua.',
  'Que o corpo seja saudável.',
  'Que a mente seja serena.',
  'Que o sentimento seja puro.',
  'Que a intenção seja boa.',
  'Que a ação seja justa.',
  'Que a palavra seja verdadeira.',
  'Que o pensamento seja elevado.',
  'Que o gesto seja de amor.',
  'Que o olhar seja de paz.',
  'Que o sorriso seja sincero.',
  'Que o abraço seja acolhedor.',
  'Que a mão seja estendida.',
  'Que o ouvido seja atento.',
  'Que o coração seja generoso.',
  'Que a alma seja luminosa.',
  'Que o espírito seja livre.',
  'Bom dia com axé!',
  'Boa tarde com luz!',
  'Boa noite com paz!',
  'Que seu dia seja abençoado!',
  'Que sua noite seja tranquila!',
  'Que sua semana seja de luz!',
  'Que seu mês seja próspero!',
  'Que seu ano seja abençoado!',
  'Que sua vida seja plena!',
  'Que seu caminho seja de luz!',
  'Que seu coração encontre paz!',
  'Que sua alma encontre luz!',
  'Que seu espírito evolua!',
  'Que você receba muitas bênçãos!',
  'Que você multiplique seu axé!',
  'Que você fortaleça sua fé!',
  'Que você expanda seu amor!',
  'Que você difunda sua luz!',
  'Que você construa sua paz!',
  'Que você pratique a caridade!',
  'Que você cultive a humildade!',
  'Que você expresse gratidão!',
  'Que você busque evolução!',
  'Que você faça preces!',
  'Que você receba proteção!',
  'Que você viva com amor!',
  'Que você brilhe com luz!',
  'Que você tenha paz!',
  'Que você encontre seu caminho!',
  'Que você honre seus Orixás!',
  'Que você respeite seus guias!',
  'Que você ame o próximo!',
  'Que você respeite a natureza!',
  'Que você preserve a tradição!',
  'Que você compartilhe o axé!',
  'Que você celebre a vida!',
  'Que você agradeça aos Orixás!',
  'Que você louve os guias!',
  'Que você participe da gira!',
  'Que você honre o congá!',
  'Que você faça oferendas com o coração!',
  'Que você cante os pontos com fé!',
  'Que você reze com devoção!',
  'Que você receba passes com gratidão!',
  'Que você desenvolva sua mediunidade com amor!',
  'Que você sirva no terreiro com dedicação!',
  'Que você acolha o próximo!',
  'Que você compartilhe sua fé!',
  'Que você ilumine seu ambiente!',
  'Que você traga paz onde for!',
  'Que você semeie amor!',
  'Que você colha bênçãos!',
  'Que você viva em axé!',
  'Que você caminhe em luz!',
  'Que você descanse em paz!',
  'Que você acorde com gratidão!',
  'Que você durma com a bênção dos Orixás!',
  'Que você sonhe com os guias!',
  'Que você acorde renovado!',
  'Que você viva o presente!',
  'Que você honre o passado!',
  'Que você construa o futuro!',
  'Que você deixe um legado de luz!',
  'Que você seja lembrado com amor!',
  'Que você inspire outros!',
  'Que você seja exemplo!',
  'Que você faça a diferença!',
  'Que você mude o que precisa mudar!',
  'Que você conserve o que precisa conservar!',
  'Que você ame incondicionalmente!',
  'Que você perdoe de coração!',
  'Que você agradeça sempre!',
  'Que você peça com humildade!',
  'Que você receba com gratidão!',
  'Que você doe com amor!',
  'Que você sirva com dedicação!',
  'Que você honre com respeito!',
  'Que você celebre com alegria!',
  'Que você viva com plenitude!',
  'Que você brilhe com intensidade!',
  'Que você ame com profundidade!',
  'Que você reze com fervor!',
  'Que você trabalhe com amor!',
  'Que você descanse em paz!',
  'Que você evolua com sabedoria!',
  'Que você cresça com humildade!',
  'Que você aprenda com os erros!',
  'Que você ensine com paciência!',
  'Que você compartilhe com generosidade!',
  'Que você proteja com cuidado!',
  'Que você cure com amor!',
  'Que você transforme com luz!',
  'Que você ilumine com presença!',
  'Que você acalente com palavra!',
  'Que você fortaleça com exemplo!',
  'Que você una com amor!',
  'Que você respeite com consciência!',
  'Que você honre com memória!',
  'Que você preserve com cuidado!',
  'Que você transmita com clareza!',
  'Que você receba com abertura!',
  'Que você doe sem medida!',
  'Que você viva com propósito!',
  'Que você encontre sua missão!',
  'Que você cumpra seu destino!',
  'Que você honre sua ancestralidade!',
  'Que você celebre sua fé!',
  'Que você multiplique seu amor!',
  'Que você expanda sua luz!',
  'Que você aprofunde sua conexão!',
  'Que você fortaleça sua fé!',
  'Que você renove seu axé!',
  'Que você purifique seu coração!',
  'Que você eleve seu espírito!',
  'Que você ilumine sua mente!',
  'Que você acalme sua alma!',
  'Que você equilibre suas energias!',
  'Que você harmonize sua vida!',
  'Que você encontre seu centro!',
  'Que você viva em equilíbrio!',
  'Que você caminhe em harmonia!',
  'Que você dance com a vida!',
  'Que você cante com o coração!',
  'Que você reze com a alma!',
  'Que você ame com tudo que é!',
  'Que você brilhe sem medo!',
  'Que você sirva com alegria!',
  'Que você honre com gratidão!',
  'Que você celebre com fé!',
  'Que você viva com axé!',
  'Laroyê!',
  'Salve!',
  'Axé no seu dia.',
  'Axé na sua casa.',
  'Axé na sua vida.',
  'Fé e luz.',
  'Paz e bem.',
  'Luz e amor.',
  'Caridade e fé.',
  'Respeito e axé.',
  'Umbanda é vida.',
  'Umbanda é força.',
  'Sou umbandista com orgulho.',
  'Minha fé é minha raiz.',
  'Meu terreiro é meu lar.',
  'Os Orixás me protegem.',
  'Os guias me orientam.',
  'A gira me renova.',
  'O congá me acolhe.',
  'A prece me fortalece.',
  'A caridade me engrandece.',
  'A humildade me ensina.',
  'A gratidão me preenche.',
  'A evolução me chama.',
  'A luz me guia.',
  'O amor me transforma.',
  'A paz me equilibra.',
  'O axé me sustenta.',
  'A natureza me nutre.',
  'Os pretos velhos me abençoam.',
  'Exu guarda meus caminhos.',
  'Pomba Gira ilumina minha vida.',
  'Oxalá me purifica.',
  'Iemanjá me acalma.',
  'Oxum me envolve em amor.',
  'Xangô me traz justiça.',
  'Ogum me dá coragem.',
  'Oxóssi me traz sabedoria.',
  'Iansã me dá força.',
  'Nanã me ensina paciência.',
  'Omulu me cura.',
  'Bênção dos Orixás.',
  'Proteção dos guias.',
  'Luz do terreiro.',
  'Axé da gira.',
  'Paz do congá.',
  'Amor de Oxum.',
  'Justiça de Xangô.',
  'Força de Ogum.',
  'Sabedoria de Oxóssi.',
  'Coragem de Iansã.',
  'Acolhida de Iemanjá.',
  'Pureza de Oxalá.',
  'Cura de Omulu.',
  'Paciência de Nanã.',
  'Abertura de Exu.',
  'Brilho de Pomba Gira.',
  'Sabedoria dos pretos velhos.',
  'Que seu axé nunca acabe.',
  'Que sua fé seja forte.',
  'Que seu amor seja grande.',
  'Que sua luz brilhe.',
  'Que sua paz reine.',
  'Que sua caridade flua.',
  'Que sua humildade cresça.',
  'Que sua gratidão transborde.',
  'Que sua evolução continue.',
  'Que sua prece seja ouvida.',
  'Que sua proteção seja real.',
  'Que sua vida seja abençoada.',
  'Que seu caminho seja de luz.',
  'Que seu coração tenha paz.',
  'Que sua alma tenha luz.',
  'Que seu espírito evolua.',
  'Bom dia com luz!',
  'Boa tarde com axé!',
  'Boa noite com paz!',
  'Saravá bom dia!',
  'Saravá boa tarde!',
  'Saravá boa noite!',
  'Axé no café da manhã.',
  'Luz no almoço.',
  'Paz no jantar.',
  'Fé ao acordar.',
  'Gratidão ao dormir.',
  'Prece ao levantar.',
  'Caridade ao longo do dia.',
  'Respeito em cada gesto.',
  'Amor em cada palavra.',
  'Paz em cada passo.',
  'Luz em cada pensamento.',
  'Axé em cada ação.',
  'Umbanda no coração.',
  'Orixás na vida.',
  'Guias no caminho.',
  'Terreiro na alma.',
  'Gira no espírito.',
  'Congá no peito.',
  'Prece nos lábios.',
  'Caridade nas mãos.',
  'Humildade no olhar.',
  'Gratidão no sorriso.',
  'Evolução na mente.',
  'Proteção no corpo.',
  'Luz na alma.',
  'Amor no coração.',
  'Paz no espírito.',
  'Axé em tudo.',
  'Fé em todos os momentos.',
  'Respeito a todos os Orixás.',
  'Honra a todos os guias.',
  'Amor a todos os irmãos.',
  'Caridade a todos os que precisam.',
  'Luz para todos os que buscam.',
  'Paz para todos os corações.',
  'Axé para todos os terreiros.',
  'Bênção para todos os filhos.',
  'Proteção para todos os caminhos.',
  'Sabedoria para todos os que aprendem.',
  'Paciência para todos os que esperam.',
  'Coragem para todos os que lutam.',
  'Força para todos os que precisam.',
  'Acolhida para todos os que chegam.',
  'Respeito para todas as crenças.',
  'Amor para toda a humanidade.',
  'Luz para todo o mundo.',
  'Paz para toda a terra.',
  'Axé para toda a vida.',
  'Saravá a todos os Orixás!',
  'Saravá a todos os guias!',
  'Saravá a todos os irmãos!',
  'Saravá a todos os terreiros!',
  'Saravá a toda a Umbanda!',
  'Axé, axé, axé!',
  'Luz, luz, luz!',
  'Paz, paz, paz!',
  'Amor, amor, amor!',
  'Fé, fé, fé!',
  'Saravá, saravá, saravá!',
  'Viva a Umbanda.',
  'Viva os Orixás.',
  'Viva os guias.',
  'Viva o terreiro.',
  'Viva a gira.',
  'Viva o axé.',
  'Viva a fé.',
  'Viva o amor.',
  'Viva a luz.',
  'Viva a paz.',
  'Viva a caridade.',
  'Viva a humildade.',
  'Viva a gratidão.',
  'Viva a evolução.',
  'Honre a Umbanda.',
  'Honre o terreiro.',
  'Honre a gira.',
  'Honre o congá.',
  'Honre a prece.',
  'Honre a oferenda.',
  'Honre o ponto cantado.',
  'Honre o passe.',
  'Honre a incorporação.',
  'Honre o desenvolvimento.',
  'Honre o trabalho mediúnico.',
  'Honre a doutrina.',
  'Honre o estudo.',
  'Honre a disciplina.',
  'Respeite a Umbanda.',
  'Respeite o terreiro.',
  'Respeite a gira.',
  'Respeite o congá.',
  'Respeite os Orixás.',
  'Respeite os guias.',
  'Respeite os pretos velhos.',
  'Respeite Exu e Pomba Gira.',
  'Respeite pai e mãe de santo.',
  'Respeite os filhos de santo.',
  'Respeite a hierarquia.',
  'Respeite o horário.',
  'Respeite o silêncio.',
  'Respeite a concentração.',
  'Respeite a prece.',
  'Respeite o ponto.',
  'Respeite a oferenda.',
  'Respeite o ritual.',
  'Respeite a tradição.',
  'Ame a Umbanda.',
  'Ame os Orixás.',
  'Ame os guias.',
  'Ame o terreiro.',
  'Ame o próximo.',
  'Ame a natureza.',
  'Ame a vida.',
  'Ame a caridade.',
  'Ame a paz.',
  'Ame a luz.',
  'Ame o axé.',
  'Ame a fé.',
  'Cuide do terreiro.',
  'Cuide do congá.',
  'Cuide da natureza.',
  'Cuide do próximo.',
  'Cuide de si mesmo.',
  'Cuide do axé.',
  'Cuide da fé.',
  'Cuide da tradição.',
  'Compartilhe o axé.',
  'Compartilhe o amor.',
  'Compartilhe a luz.',
  'Compartilhe a paz.',
  'Compartilhe a fé.',
  'Compartilhe a caridade.',
  'Compartilhe a sabedoria.',
  'Compartilhe a gratidão.',
  'Compartilhe a bênção.',
  'Celebre a vida.',
  'Celebre os Orixás.',
  'Celebre a gira.',
  'Celebre o axé.',
  'Celebre a fé.',
  'Celebre o amor.',
  'Celebre a luz.',
  'Celebre a paz.',
  'Celebre a Umbanda.',
  'Agradeça aos Orixás.',
  'Agradeça aos guias.',
  'Agradeça ao terreiro.',
  'Agradeça à vida.',
  'Agradeça à natureza.',
  'Agradeça pela fé.',
  'Agradeça pelo axé.',
  'Agradeça pelo amor.',
  'Agradeça pela luz.',
  'Agradeça pela paz.',
  'Agradeça pela proteção.',
  'Agradeça pela cura.',
  'Agradeça pela bênção.',
  'Agradeça pelo aprendizado.',
  'Reze pelos irmãos.',
  'Reze pelos guias.',
  'Reze pelos Orixás.',
  'Reze pela paz.',
  'Reze pela luz.',
  'Reze pelo amor.',
  'Reze pela cura.',
  'Reze pela proteção.',
  'Reze pela evolução.',
  'Reze pela gratidão.',
  'Trabalhe com amor.',
  'Trabalhe com fé.',
  'Trabalhe com humildade.',
  'Trabalhe com caridade.',
  'Trabalhe com dedicação.',
  'Trabalhe com respeito.',
  'Trabalhe com gratidão.',
  'Trabalhe com axé.',
  'Sirva com amor.',
  'Sirva com humildade.',
  'Sirva com caridade.',
  'Sirva com dedicação.',
  'Sirva com fé.',
  'Sirva com gratidão.',
  'Sirva com respeito.',
  'Sirva com axé.',
  'Acolha com amor.',
  'Acolha com respeito.',
  'Acolha com caridade.',
  'Acolha com paz.',
  'Acolha com luz.',
  'Proteja com fé.',
  'Proteja com prece.',
  'Proteja com axé.',
  'Proteja com amor.',
  'Cure com amor.',
  'Cure com prece.',
  'Cure com ervas.',
  'Cure com passe.',
  'Cure com axé.',
  'Transforme com luz.',
  'Transforme com amor.',
  'Transforme com fé.',
  'Ilumine com presença.',
  'Ilumine com palavra.',
  'Ilumine com gesto.',
  'Fortaleça com exemplo.',
  'Fortaleça com fé.',
  'Fortaleça com axé.',
  'Una com amor.',
  'Una com respeito.',
  'Una com caridade.',
  'Preserve a tradição.',
  'Preserve o terreiro.',
  'Preserve a natureza.',
  'Preserve o axé.',
  'Preserve a sabedoria.',
  'Transmita a luz.',
  'Transmita o amor.',
  'Transmita a paz.',
  'Transmita a fé.',
  'Transmita o axé.',
  'Receba com gratidão.',
  'Receba com humildade.',
  'Receba com amor.',
  'Doe com amor.',
  'Doe com gratidão.',
  'Doe com humildade.',
  'Doe sem medida.',
  'Evolua com sabedoria.',
  'Evolua com humildade.',
  'Evolua com fé.',
  'Evolua com amor.',
  'Cresça com paciência.',
  'Cresça com humildade.',
  'Cresça com fé.',
  'Aprenda com os guias.',
  'Aprenda com os Orixás.',
  'Aprenda com os pretos velhos.',
  'Ensine com paciência.',
  'Ensine com amor.',
  'Ensine com exemplo.',
  'Proteja com cuidado.',
  'Proteja com prece.',
  'Proteja com axé.',
  'Equilibre com fé.',
  'Equilibre com amor.',
  'Equilibre com paz.',
  'Harmonize com luz.',
  'Harmonize com axé.',
  'Purifique com prece.',
  'Purifique com ervas.',
  'Purifique com amor.',
  'Eleve com fé.',
  'Eleve com gratidão.',
  'Eleve com caridade.',
  'Renove com a gira.',
  'Renove com a prece.',
  'Renove com o axé.',
  'Conecte com os Orixás.',
  'Conecte com os guias.',
  'Conecte com a natureza.',
  'Conecte com o divino.',
  'Abra o coração.',
  'Abra os caminhos.',
  'Abra para o amor.',
  'Abra para a luz.',
  'Feche para o mal.',
  'Feche para a inveja.',
  'Feche para a negatividade.',
  'Deixe a luz entrar.',
  'Deixe o amor entrar.',
  'Deixe os Orixás guiarem.',
  'Deixe os guias trabalharem.',
  'Permita a evolução.',
  'Permita a cura.',
  'Permita a transformação.',
  'Aceite a bênção.',
  'Aceite o axé.',
  'Aceite a proteção.',
  'Aceite o amor.',
  'Aceite a luz.',
  'Mantenha a fé.',
  'Mantenha o axé.',
  'Mantenha a humildade.',
  'Mantenha a gratidão.',
  'Mantenha a paz.',
  'Mantenha o respeito.',
  'Mantenha a caridade.',
  'Mantenha a prece.',
  'Mantenha a conexão.',
  'Mantenha a luz.',
  'Compartilhe a bênção.',
  'Compartilhe a proteção.',
  'Compartilhe a cura.',
  'Compartilhe a sabedoria.',
  'Compartilhe a alegria.',
  'Compartilhe a esperança.',
  'Compartilhe a coragem.',
  'Compartilhe a força.',
  'Compartilhe a paciência.',
  'Compartilhe a compreensão.',
  'Compartilhe o perdão.',
  'Compartilhe a misericórdia.',
  'Compartilhe a compaixão.',
  'Compartilhe a solidariedade.',
  'Compartilhe a união.',
  'Compartilhe a fraternidade.',
  'Que a gira seja abençoada.',
  'Que o congá seja respeitado.',
  'Que o terreiro seja luz.',
  'Que os filhos sejam felizes.',
  'Que os guias trabalhem.',
  'Que os Orixás reinem.',
  'Que o axé se multiplique.',
  'Que a fé se fortaleça.',
  'Que o amor se expanda.',
  'Que a luz se difunda.',
  'Que a paz se construa.',
  'Que a caridade se pratique.',
  'Que a humildade se cultive.',
  'Que a gratidão se expresse.',
  'Que a evolução se busque.',
  'Que a prece seja constante.',
  'Que a proteção seja invocada.',
  'Que a vida seja celebrada.',
  'Que o caminho seja percorrido.',
  'Que o coração esteja aberto.',
  'Que a alma esteja em paz.',
  'Que o espírito evolua.',
  'Que o corpo seja templo.',
  'Que a mente seja clara.',
  'Que o sentimento seja puro.',
  'Que a intenção seja boa.',
  'Que a ação seja justa.',
  'Que a palavra seja verdadeira.',
  'Que o pensamento seja elevado.',
  'Que o gesto seja de amor.',
  'Que o olhar seja de paz.',
  'Que o sorriso seja sincero.',
  'Que o abraço seja acolhedor.',
  'Que a mão seja estendida.',
  'Que o ouvido seja atento.',
  'Que o coração seja generoso.',
  'Que a alma seja luminosa.',
  'Que o espírito seja livre.',
  'Umbanda de luz e amor.',
  'Terreiro de paz e fé.',
  'Gira de axé e caridade.',
  'Congá de respeito e honra.',
  'Prece de gratidão e entrega.',
  'Oferenda de amor e devoção.',
  'Ponto de fé e conexão.',
  'Passe de cura e luz.',
  'Incorporação de serviço e amor.',
  'Desenvolvimento de paciência e humildade.',
  'Doutrina de sabedoria e respeito.',
  'Estudo de crescimento e evolução.',
  'Disciplina de compromisso e dedicação.',
  'Trabalho de luz e caridade.',
];
